### ISSUE TITLE
How can I get bls_data.xlsx?

### ISSUE THREAD

**Issue by Jaclong** [KaroRonty/SelfOrganizingStockMarket#1]
Hi, I am trying to do this analysis again. There is a data bls_data.xlsx which loaded in local path. How can I get the data. Thank you

**Comment by KaroRonty** [comment]
Available here: https://data.bls.gov/timeseries/LNS14000000
Select years 1948-2018 and click download xlsx.

**Comment by KaroRonty** [comment]
You also need to click "go" before clicking download.

**Comment by Jaclong** [comment]
Thanks for helping. I make it!
